### PR TITLE
TNT-36959 Rename to official name

### PR DESCRIPTION
**Pull request by 5amfung**
Rename to official name.

### CODE REVIEW

**Comment by gregggreg** [comment]
Looks good. But if we are going so far as to rename the classes in `com.adobe.target.edge.client.local` we might as well rename that package as well.

**Comment by 5amfung** [comment]
@gregggreg Renamed `com.adobe.target.edge.client.local` to `....client.ondevice`.

**Review by gregggreg — APPROVED** [review]
Looks good, thanks.

**Comment by gregggreg** [comment]
Looks good

**Pull request merged**
